hooks:
  custom-items:
    prevent-mending: false
    prevent-furnace-fuel: true
  jobs:
    place-break:
      enable-patch: false
      world-bypass:
        - Mapart
  plotsquared:
    # Stops players who aren't a member/owner of the plot from making maps of it
    prevent-maps-for-non-owners: true