hooks:
  custom-items:
    prevent-mending: false
    prevent-furnace-fuel: true
  jobs:
    place-break:
      enable-patch: false
      world-bypass: []
  denizen:
    # Enable the DaisyLib hook?
    daisylib: true
    # Enable the EvenMoreFish hook?
    evenmorefish: true