name: AdminTools
version: '${project.version} ${buildDescription}'
main: uk.firedev.admintools.AdminTools
api-version: '1.20'
author: FireML
description: ${project.description}
folia-supported: true
dependencies:
  server:
    DaisyLib:
      required: true
      load: BEFORE
    CMI:
      required: false
      load: BEFORE
    EvenMoreFish:
      required: false
      load: BEFORE
    Multiverse-Core:
      required: false
      load: BEFORE
    Denizen:
      required: false
      load: BEFORE
    HuskChat:
      required: false
      load: BEFORE
    Jobs:
      required: false
      load: BEFORE