name: AdminTools
version: '${project.version} ${buildDescription}'
main: uk.firedev.admintools.AdminTools
api-version: '1.20'
depend:
  - DaisyLib
softdepend:
  - EvenMoreFish
  - CMI
  - Multiverse-Core
  - Denizen
  - VotingPlugin
author: FireML
description: ${project.description}
folia-supported: true